spring:
  datasource:
    url: jdbc:mysql://localhost:13307/demo
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost
          jwk-set-uri: http://localhost

logging:
  level:
    org:
      springframework:
        security: DEBUG
