FROM mysql:8.0.35-oracle

USER 0

COPY ./conf/replica/my-ext.cnf /etc/mysql/conf.d/my.cnf
COPY ./init/mysql/replica /init-mysql
COPY ./init/db /init-db
COPY ./init/init.sh /docker-entrypoint-initdb.d/01-init.sh
#COPY ./init/seeding.sh /docker-entrypoint-initdb.d/02-seeding.sh

ENV TZ=UTC
ENV MYSQL_ROOT_PASSWORD=1234
